/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'todayBookingCount' : bigint,
  'todayRevenue' : bigint,
  'weekRevenue' : bigint,
}
export interface BlockedSlot {
  'id' : bigint,
  'startTime' : bigint,
  'endTime' : bigint,
  'resourceId' : bigint,
  'reason' : string,
}
export interface Booking {
  'id' : bigint,
  'startTime' : bigint,
  'status' : BookingStatus,
  'durationMins' : bigint,
  'userName' : string,
  'couponCode' : string,
  'paymentMethod' : PaymentMethod,
  'resourceId' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'userPhone' : string,
  'resourceName' : string,
  'resourceType' : ResourceType,
  'totalAmount' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Coupon {
  'code' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export type PaymentMethod = { 'upi' : null } |
  { 'creditCard' : null } |
  { 'cash' : null };
export interface Resource {
  'id' : bigint,
  'name' : string,
  'basePricePerHalfHour' : bigint,
  'isActive' : boolean,
  'resourceType' : ResourceType,
  'basePricePerHour' : bigint,
}
export type ResourceType = { 'ps4Console' : null } |
  { 'ps5Console' : null } |
  { 'poolTable' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoupon' : ActorMethod<[string, bigint], Coupon>,
  'addResource' : ActorMethod<[string, ResourceType, bigint, bigint], Resource>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockSlot' : ActorMethod<[bigint, bigint, bigint, string], BlockedSlot>,
  'cancelBooking' : ActorMethod<[bigint], Booking>,
  'createBooking' : ActorMethod<
    [Principal, string, string, bigint, bigint, bigint, PaymentMethod, string],
    Booking
  >,
  'getActiveCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllBlockedSlots' : ActorMethod<[], Array<BlockedSlot>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAvailableSlots' : ActorMethod<[bigint, bigint, bigint], Array<bigint>>,
  'getBlockedSlotsForResource' : ActorMethod<[bigint], Array<BlockedSlot>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoupon' : ActorMethod<[string], Coupon>,
  'getResource' : ActorMethod<[bigint], Resource>,
  'getResourcesByType' : ActorMethod<[ResourceType], Array<Resource>>,
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], Booking>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];