/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coupon = IDL.Record({
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const ResourceType = IDL.Variant({
  'snookerTable' : IDL.Null,
  'ps4Console' : IDL.Null,
  'ps5Console' : IDL.Null,
  'poolTable' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'basePricePerHalfHour' : IDL.Nat,
  'isActive' : IDL.Bool,
  'resourceType' : ResourceType,
  'basePricePerHour' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlockedSlot = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'endTime' : IDL.Int,
  'resourceId' : IDL.Nat,
  'reason' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'creditCard' : IDL.Null,
  'cash' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : BookingStatus,
  'durationMins' : IDL.Nat,
  'userName' : IDL.Text,
  'couponCode' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'resourceId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'userPhone' : IDL.Text,
  'resourceName' : IDL.Text,
  'resourceType' : ResourceType,
  'totalAmount' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'todayBookingCount' : IDL.Nat,
  'todayRevenue' : IDL.Nat,
  'weekRevenue' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoupon' : IDL.Func([IDL.Text, IDL.Nat], [Coupon], []),
  'addResource' : IDL.Func(
      [IDL.Text, ResourceType, IDL.Nat, IDL.Nat],
      [Resource],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockSlot' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Int, IDL.Text],
      [BlockedSlot],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'createBooking' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        PaymentMethod,
        IDL.Text,
      ],
      [Booking],
      [],
    ),
  'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllBlockedSlots' : IDL.Func([], [IDL.Vec(BlockedSlot)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Int],
      [IDL.Vec(IDL.Int)],
      ['query'],
    ),
  'getBlockedSlotsForResource' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BlockedSlot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [Coupon], ['query']),
  'getResource' : IDL.Func([IDL.Nat], [Resource], ['query']),
  'getResourcesByType' : IDL.Func(
      [ResourceType],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [Booking], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coupon = IDL.Record({
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const ResourceType = IDL.Variant({
    'snookerTable' : IDL.Null,
    'ps4Console' : IDL.Null,
    'ps5Console' : IDL.Null,
    'poolTable' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'basePricePerHalfHour' : IDL.Nat,
    'isActive' : IDL.Bool,
    'resourceType' : ResourceType,
    'basePricePerHour' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlockedSlot = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'endTime' : IDL.Int,
    'resourceId' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'creditCard' : IDL.Null,
    'cash' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : BookingStatus,
    'durationMins' : IDL.Nat,
    'userName' : IDL.Text,
    'couponCode' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'resourceId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'userPhone' : IDL.Text,
    'resourceName' : IDL.Text,
    'resourceType' : ResourceType,
    'totalAmount' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'todayBookingCount' : IDL.Nat,
    'todayRevenue' : IDL.Nat,
    'weekRevenue' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoupon' : IDL.Func([IDL.Text, IDL.Nat], [Coupon], []),
    'addResource' : IDL.Func(
        [IDL.Text, ResourceType, IDL.Nat, IDL.Nat],
        [Resource],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockSlot' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int, IDL.Text],
        [BlockedSlot],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'createBooking' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          PaymentMethod,
          IDL.Text,
        ],
        [Booking],
        [],
      ),
    'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllBlockedSlots' : IDL.Func([], [IDL.Vec(BlockedSlot)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int],
        [IDL.Vec(IDL.Int)],
        ['query'],
      ),
    'getBlockedSlotsForResource' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BlockedSlot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [Coupon], ['query']),
    'getResource' : IDL.Func([IDL.Nat], [Resource], ['query']),
    'getResourcesByType' : IDL.Func(
        [ResourceType],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [Booking], []),
  });
};

export const init = ({ IDL }) => { return []; };