/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminStats {
    todayBookingCount: bigint;
    todayRevenue: bigint;
    weekRevenue: bigint;
}
export interface Resource {
    id: bigint;
    name: string;
    basePricePerHalfHour: bigint;
    isActive: boolean;
    resourceType: ResourceType;
    basePricePerHour: bigint;
}
export interface Booking {
    id: bigint;
    startTime: bigint;
    status: BookingStatus;
    durationMins: bigint;
    userName: string;
    couponCode: string;
    paymentMethod: PaymentMethod;
    resourceId: bigint;
    userId: Principal;
    createdAt: bigint;
    userPhone: string;
    resourceName: string;
    resourceType: ResourceType;
    totalAmount: bigint;
}
export interface Coupon {
    code: string;
    discountPercent: bigint;
    isActive: boolean;
}
export interface BlockedSlot {
    id: bigint;
    startTime: bigint;
    endTime: bigint;
    resourceId: bigint;
    reason: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    upi = "upi",
    creditCard = "creditCard",
    cash = "cash"
}
export enum ResourceType {
    ps4Console = "ps4Console",
    ps5Console = "ps5Console",
    poolTable = "poolTable"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoupon(code: string, discountPercent: bigint): Promise<Coupon>;
    addResource(name: string, resourceType: ResourceType, basePricePerHour: bigint, basePricePerHalfHour: bigint): Promise<Resource>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockSlot(resourceId: bigint, startTime: bigint, endTime: bigint, reason: string): Promise<BlockedSlot>;
    cancelBooking(bookingId: bigint): Promise<Booking>;
    createBooking(userId: Principal, userName: string, userPhone: string, resourceId: bigint, durationMins: bigint, startTime: bigint, paymentMethod: PaymentMethod, couponCode: string): Promise<Booking>;
    getActiveCoupons(): Promise<Array<Coupon>>;
    getAdminStats(): Promise<AdminStats>;
    getAllBlockedSlots(): Promise<Array<BlockedSlot>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllResources(): Promise<Array<Resource>>;
    getAvailableSlots(resourceId: bigint, dateStartNanos: bigint, dateEndNanos: bigint): Promise<Array<bigint>>;
    getBlockedSlotsForResource(resourceId: bigint): Promise<Array<BlockedSlot>>;
    getBooking(bookingId: bigint): Promise<Booking>;
    getCallerUserRole(): Promise<UserRole>;
    getCoupon(code: string): Promise<Coupon>;
    getResource(resourceId: bigint): Promise<Resource>;
    getResourcesByType(resourceType: ResourceType): Promise<Array<Resource>>;
    getUserBookings(userId: Principal): Promise<Array<Booking>>;
    initializeSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    updateBookingStatus(bookingId: bigint, status: BookingStatus): Promise<Booking>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, PaymentMethod as _PaymentMethod, Resource as _Resource, ResourceType as _ResourceType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoupon(arg0: string, arg1: bigint): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupon(arg0, arg1);
            return result;
        }
    }
    async addResource(arg0: string, arg1: ResourceType, arg2: bigint, arg3: bigint): Promise<Resource> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Resource_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Resource_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockSlot(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<BlockedSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.blockSlot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockSlot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: Principal, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: PaymentMethod, arg7: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PaymentMethod_n15(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PaymentMethod_n15(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCoupons();
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllBlockedSlots(): Promise<Array<BlockedSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlockedSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlockedSlots();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1, arg2);
            return result;
        }
    }
    async getBlockedSlotsForResource(arg0: bigint): Promise<Array<BlockedSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedSlotsForResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedSlotsForResource(arg0);
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupon(arg0: string): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupon(arg0);
            return result;
        }
    }
    async getResource(arg0: bigint): Promise<Resource> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_Resource_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_Resource_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesByType(arg0: ResourceType): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByType(to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByType(to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _BookingStatus;
    durationMins: bigint;
    userName: string;
    couponCode: string;
    paymentMethod: _PaymentMethod;
    resourceId: bigint;
    userId: Principal;
    createdAt: bigint;
    userPhone: string;
    resourceName: string;
    resourceType: _ResourceType;
    totalAmount: bigint;
}): {
    id: bigint;
    startTime: bigint;
    status: BookingStatus;
    durationMins: bigint;
    userName: string;
    couponCode: string;
    paymentMethod: PaymentMethod;
    resourceId: bigint;
    userId: Principal;
    createdAt: bigint;
    userPhone: string;
    resourceName: string;
    resourceType: ResourceType;
    totalAmount: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_BookingStatus_n11(_uploadFile, _downloadFile, value.status),
        durationMins: value.durationMins,
        userName: value.userName,
        couponCode: value.couponCode,
        paymentMethod: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.paymentMethod),
        resourceId: value.resourceId,
        userId: value.userId,
        createdAt: value.createdAt,
        userPhone: value.userPhone,
        resourceName: value.resourceName,
        resourceType: from_candid_ResourceType_n5(_uploadFile, _downloadFile, value.resourceType),
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    basePricePerHalfHour: bigint;
    isActive: boolean;
    resourceType: _ResourceType;
    basePricePerHour: bigint;
}): {
    id: bigint;
    name: string;
    basePricePerHalfHour: bigint;
    isActive: boolean;
    resourceType: ResourceType;
    basePricePerHour: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        basePricePerHalfHour: value.basePricePerHalfHour,
        isActive: value.isActive,
        resourceType: from_candid_ResourceType_n5(_uploadFile, _downloadFile, value.resourceType),
        basePricePerHour: value.basePricePerHour
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    creditCard: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "creditCard" in value ? PaymentMethod.creditCard : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ps4Console: null;
} | {
    ps5Console: null;
} | {
    poolTable: null;
}): ResourceType {
    return "ps4Console" in value ? ResourceType.ps4Console : "ps5Console" in value ? ResourceType.ps5Console : "poolTable" in value ? ResourceType.poolTable : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n3(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    creditCard: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.creditCard ? {
        creditCard: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    ps4Console: null;
} | {
    ps5Console: null;
} | {
    poolTable: null;
} {
    return value == ResourceType.ps4Console ? {
        ps4Console: null
    } : value == ResourceType.ps5Console ? {
        ps5Console: null
    } : value == ResourceType.poolTable ? {
        poolTable: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
